### ISSUE TITLE
SAML21

### ISSUE THREAD

**Issue by karu2003** [LibreSolar/bq769x0_mbed_lib#5]
Good afternoon,

I'm doing BMS 5S with SAML21. I can not build your library bq769x0.
Tell me which version mbed did you use?
Did you build the project online or mbed cli?

Thank you.
Andrew.

**Comment by martinjaeger** [comment]
Hi Andrew.

I use PlatformIO IDE and the built-in mbed-os. Should be something above version 5.3.

Have a look at the BMS24V_Software repository to see how the lib can be used.

Martin

Am 18. Juni 2017 09:01:03 MESZ, schrieb karu2003 <notifications@github.com>:

**Comment by karu2003** [comment]
Thank you Martin,

Mbed os does not support Atmel SAML21.
Support is only in mbed-dev.

PlatformIO + Atom.
Interesting IDE. thanks.
How do you export from Online to PlatformIO? GCC or?
Are you using the Clang?
Andrew.

**Comment by karu2003** [comment]
I replaced the mbed-os on mbed-dev removed the work with the display and replaced the names of the PINS.
Error Mbed disappeared.
But there is an error in the library.
Error: Data member initializer is not allowed in "bq769x0_mbed_lib/bq769x0.h", Line: 114, Col: 30
Build online
>>> bool alertInterruptFlag = true;   // init with true to check and clear errors at start-up  
:(

**Comment by martinjaeger** [comment]
Please check if the error disappeared with the update.

I don't export from Online mbed IDE to PlatformIO, but use PlatformIO IDE with GCC directly. Never tried the mbed online IDE.
